import { QuestionV2 } from "../../quiz-types";

export const csc221Chapter6: QuestionV2[] = [
  {
    id: "csc221_258",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "What is the primary purpose of floating-point representation in computing?",
    options: [
      "To represent only positive integers accurately",
      "To encode numbers in a format that handles very large and very small values",
      "To increase the speed of simple addition by removing decimals",
      "To store text data using binary scientific notation",
    ],
    correctAnswer: 1,
    explanation:
      "Floating point representation is used to encode numbers in a format that can handle very large and very small values, based on scientific notation.",
  },
  {
    id: "csc221_259",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Floating-point representation allows for a trade-off between which two factors?",
    options: [
      "Speed and Cost",
      "Memory and Storage",
      "Range and Precision",
      "Input and Output",
    ],
    correctAnswer: 2,
    explanation:
      "In computing, floating-point representation allows for a trade-off between the range of numbers that can be represented and the precision of those numbers.",
  },
  {
    id: "csc221_260",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Floating point numbers are also commonly referred to as 'real numbers'.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation:
      "The document states that a floating-point number is also called a real number.",
  },
  {
    id: "csc221_261",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "In the scientific notation formula $M \\times B^E$, what does 'M' represent?",
    options: [
      "Multiplier",
      "Mantissa (Significand)",
      "Magnitude",
      "Memory allocation",
    ],
    correctAnswer: 1,
    explanation:
      "In the expression $M \\times B^E$, $M$ is the Mantissa or Significand, which represents the significant digits of the number.",
  },
  {
    id: "csc221_262",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "In the scientific notation formula $M \\times B^E$, what does 'B' represent?",
    options: ["Binary digit", "Bias value", "Base (Radix)", "Bit length"],
    correctAnswer: 2,
    explanation:
      "In the expression $M \\times B^E$, $B$ is the Base or Radix (e.g., 10 for decimal, 2 for binary).",
  },
  {
    id: "csc221_263",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "The exponent 'E' in floating-point notation determines the range of the number representation.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation:
      "The exponent 'E' determines the range of values that can be represented by the floating-point number.",
  },
  {
    id: "csc221_264",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "What is the most widely used standard for floating-point computation?",
    options: ["ASCII 8-bit", "ISO 9001", "IEEE 754", "EBCDIC-64"],
    correctAnswer: 2,
    explanation:
      "The IEEE 754 standard is the most common representation for real numbers on modern computers.",
  },
  {
    id: "csc221_265",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Which component is NOT part of the basic structure of an IEEE 754 floating-point number?",
    options: [
      "Sign bit",
      "Biased Exponent",
      "Fraction (Mantissa)",
      "Check bit",
    ],
    correctAnswer: 3,
    explanation:
      "The standard components are the Sign, the Biased Exponent, and the Fraction/Mantissa.",
  },
  {
    id: "csc221_266",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "In floating-point representation, what does a sign bit of '1' indicate?",
    options: [
      "The number is positive",
      "The number is negative",
      "The number is zero",
      "The number is an exponent",
    ],
    correctAnswer: 1,
    explanation:
      "A sign bit of 0 represents a positive number, while 1 represents a negative number.",
  },
  {
    id: "csc221_267",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "How many total bits are used in Single Precision floating-point representation?",
    options: ["16 bits", "32 bits", "64 bits", "128 bits"],
    correctAnswer: 1,
    explanation: "Single Precision (binary32) uses a total of 32 bits.",
  },
  {
    id: "csc221_268",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "In Single Precision (32-bit), how many bits are allocated specifically for the exponent?",
    options: ["1 bit", "8 bits", "11 bits", "23 bits"],
    correctAnswer: 1,
    explanation:
      "Single Precision allocates 1 bit for the sign, 8 bits for the exponent, and 23 bits for the fraction.",
  },
  {
    id: "csc221_269",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "In Single Precision (32-bit), how many bits are allocated for the fraction (mantissa)?",
    options: ["8 bits", "11 bits", "23 bits", "52 bits"],
    correctAnswer: 2,
    explanation:
      "The fraction part of a 32-bit Single Precision number uses 23 bits.",
  },
  {
    id: "csc221_270",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Double Precision floating-point representation uses a total of 64 bits.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation: "Double Precision (binary64) is a 64-bit format.",
  },
  {
    id: "csc221_271",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "How many bits are used for the exponent in Double Precision (64-bit) representation?",
    options: ["8 bits", "11 bits", "23 bits", "52 bits"],
    correctAnswer: 1,
    explanation: "In Double Precision, the exponent field is 11 bits wide.",
  },
  {
    id: "csc221_272",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "How many bits are used for the fraction in Double Precision (64-bit) representation?",
    options: ["11 bits", "23 bits", "52 bits", "63 bits"],
    correctAnswer: 2,
    explanation:
      "Double Precision uses 52 bits for the fractional part (mantissa).",
  },
  {
    id: "csc221_273",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "What is 'Normalization' in the context of floating-point numbers?",
    options: [
      "Adjusting the base to always be 10",
      "Adjusting the exponent so the leading digit of the mantissa is non-zero",
      "Converting all negative numbers to positive for easier storage",
      "Rounding every number to the nearest integer",
    ],
    correctAnswer: 1,
    explanation:
      "Normalization is the process of adjusting the exponent so that the leading digit of the mantissa is non-zero.",
  },
  {
    id: "csc221_274",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "In binary normalized form, what is the implicit leading bit before the radix point?",
    options: ["0", "1", "The sign bit", "There is no implicit bit"],
    correctAnswer: 1,
    explanation:
      "For normalized numbers, the leading bit is always an implicit 1, which saves one bit of storage.",
  },
  {
    id: "csc221_275",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "For denormalized numbers, the leading bit is 0.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation:
      "The slides specify that while normalized numbers have an implicit 1, denormalized numbers have a leading 0.",
  },
  {
    id: "csc221_276",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Why is a 'Bias' added to the exponent in IEEE 754 representation?",
    options: [
      "To make the number larger for better accuracy",
      "To allow the representation of both positive and negative exponents using unsigned integers",
      "To correct errors caused by rounding and truncation",
      "To identify whether the number is a whole integer or a fraction",
    ],
    correctAnswer: 1,
    explanation:
      "A bias is used so that the stored exponent is always a non-negative integer, even if the actual exponent is negative.",
  },
  {
    id: "csc221_277",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "What is the bias value for Single Precision (32-bit) floating-point numbers?",
    options: ["127", "128", "1023", "1024"],
    correctAnswer: 0,
    explanation: "The bias for single precision is 127.",
  },
  {
    id: "csc221_278",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "What is the bias value for Double Precision (64-bit) floating-point numbers?",
    options: ["127", "255", "1023", "2047"],
    correctAnswer: 2,
    explanation: "The bias for double precision is 1023.",
  },
  {
    id: "csc221_279",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "If a single precision number has a stored exponent of 130, what is its actual exponent value?",
    options: ["130", "257", "3", "-127"],
    correctAnswer: 2,
    explanation:
      "Actual Exponent = Stored Exponent - Bias. Here, $130 - 127 = 3$.",
  },
  {
    id: "csc221_280",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Precision is determined by the number of bits in the exponent field.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 1,
    explanation:
      "Precision is determined by the number of bits in the mantissa (fraction), while range is determined by the exponent.",
  },
  {
    id: "csc221_281",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Which of the following is an advantage of floating-point representation?",
    options: [
      "It provides exact representation for all decimal fractions",
      "It can represent a very wide range of very large and very small numbers",
      "It uses less memory than standard integer representation",
      "It eliminates the need for a Central Processing Unit",
    ],
    correctAnswer: 1,
    explanation:
      "One of the main advantages is the wide range, allowing for the representation of extremely large or small values.",
  },
  {
    id: "csc221_282",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Rounding and truncation can lead to which issue in floating-point numbers?",
    options: [
      "Overhead errors",
      "Standardization errors",
      "Precision errors",
      "Binary logic errors",
    ],
    correctAnswer: 2,
    explanation:
      "Floating point numbers can suffer from precision errors due to rounding and truncation.",
  },
  {
    id: "csc221_283",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Operations involving floating-point numbers are generally faster than integer operations.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 1,
    explanation:
      "According to the 'Disadvantages' slide, operations involving floating-point numbers can be slower and require more memory compared to integer operations.",
  },
  {
    id: "csc221_284",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Which field extensively applies floating-point representation for accurate measurements and simulations?",
    options: [
      "Word processing",
      "Engineering",
      "Database indexing",
      "Firmware updating",
    ],
    correctAnswer: 1,
    explanation:
      "Floating point is applied in engineering fields such as aerospace, mechanical engineering, and electronics.",
  },
  {
    id: "csc221_285",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Floating-point representation is essential in computer graphics for rendering and manipulating data.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation:
      "Precise calculations needed for rendering graphical data make floating-point essential in graphics.",
  },
  {
    id: "csc221_286",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "What does NaN stand for in floating-point terminology?",
    options: [
      "Negative and Null",
      "Not a Number",
      "Next available Node",
      "Normalized and Neutral",
    ],
    correctAnswer: 1,
    explanation:
      "NaN (Not a Number) is a special value used to represent undefined results (like 0/0).",
  },
  {
    id: "csc221_287",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Floating-point numbers can represent positive and negative infinity.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation:
      "The IEEE 754 standard includes special representations for positive and negative infinity.",
  },
  {
    id: "csc221_288",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "In Single Precision, the largest possible value for the biased exponent (before special cases) is 255.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation: "An 8-bit exponent can range from 0 to 255.",
  },
  {
    id: "csc221_289",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Which of these is considered a disadvantage of floating-point representation?",
    options: [
      "Standardization through IEEE 754",
      "Complexity requiring more computational resources",
      "The ability to represent very small numbers",
      "Compatibility across different programming languages",
    ],
    correctAnswer: 1,
    explanation:
      "Floating point systems are more complex than fixed-point systems and require more hardware/computational resources.",
  },
  {
    id: "csc221_290",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Single precision is suitable for which type of applications?",
    options: [
      "Applications where memory is unlimited",
      "Applications where precision is more important than speed",
      "Applications where range and precision are moderately important (e.g., standard scientific work)",
      "Applications that only use whole integers",
    ],
    correctAnswer: 2,
    explanation:
      "Single precision provides a balance suitable for many scientific and engineering tasks.",
  },
  {
    id: "csc221_291",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "The term 'significand' is another name for the mantissa.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation: "The mantissa is also called the significand.",
  },
  {
    id: "csc221_292",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "What is the result of increasing the number of bits in the fraction part?",
    options: [
      "The range of the number increases",
      "The precision of the number increases",
      "The speed of calculation increases",
      "The sign of the number changes",
    ],
    correctAnswer: 1,
    explanation:
      "More bits in the fraction/mantissa allow for higher precision (more significant digits).",
  },
  {
    id: "csc221_293",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "What is the result of increasing the number of bits in the exponent part?",
    options: [
      "The precision of the number increases",
      "The range of the number increases",
      "The bias value decreases",
      "The number becomes denormalized",
    ],
    correctAnswer: 1,
    explanation:
      "A larger exponent field allows for a much wider range of values (larger maximums and smaller minimums).",
  },
  {
    id: "csc221_294",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Floating-point numbers can represent 'zero' in both positive and negative forms (+0 and -0).",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation: "The IEEE 754 standard supports signed zeros.",
  },
  {
    id: "csc221_295",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Which of these numbers is NOT normalized in binary?",
    options: [
      "$1.011 \\times 2^5$",
      "$0.110 \\times 2^3$",
      "$1.000 \\times 2^0$",
      "$1.111 \\times 2^{-10}$",
    ],
    correctAnswer: 1,
    explanation:
      "Normalized binary numbers must have a '1' before the decimal point ($1.xxx$).",
  },
  {
    id: "csc221_296",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Single precision uses a 23-bit mantissa, but it effectively has 24 bits of precision because of the implicit leading bit.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation:
      "The implicit leading 1 allows the 23 stored bits to represent a 24-bit significand.",
  },
  {
    id: "csc221_297",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "What is the binary base (radix) used in computer floating-point systems?",
    options: ["10", "8", "2", "16"],
    correctAnswer: 2,
    explanation:
      "Computers use base 2 (binary) for floating-point representation.",
  },
  {
    id: "csc221_298",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Double precision is always necessary for every simple calculation.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 1,
    explanation:
      "Double precision is often unnecessary for simple calculations and requires more memory/resources; single precision is often sufficient.",
  },
  {
    id: "csc221_299",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "A number very close to zero, like $1.23 \\times 10^{-88}$, requires floating-point representation to be stored accurately.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation:
      "Extremely small fractional values are exactly why floating-point formats were developed.",
  },
  {
    id: "csc221_300",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "How many bits are used for the sign in Double Precision (64-bit)?",
    options: ["1 bit", "2 bits", "8 bits", "11 bits"],
    correctAnswer: 0,
    explanation:
      "Both single and double precision use exactly 1 bit for the sign.",
  },
  {
    id: "csc221_301",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "The IEEE 754 standard ensures consistency across different systems and programming languages.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation:
      "Standardization ensures that a floating-point calculation on one computer gives the same result on another.",
  },
  {
    id: "csc221_302",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "What is a 'Denormalized' number?",
    options: [
      "A number that is too large to fit in 64 bits",
      "A number where the leading bit is 0, used for values very close to zero",
      "A number stored without a bias",
      "A number that has been rounded to the nearest power of 10",
    ],
    correctAnswer: 1,
    explanation:
      "Denormalized numbers allow for the representation of values smaller than the smallest normalized number, using a leading 0.",
  },
  {
    id: "csc221_303",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Truncation involves shortening a number by dropping digits without rounding.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation:
      "Truncation is the simplest form of shortening but often leads to precision issues.",
  },
  {
    id: "csc221_304",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Which of the following would benefit most from Double Precision?",
    options: [
      "Counting the number of items in a shopping cart",
      "High-precision scientific simulations of planetary orbits",
      "Storing a user's age in a database",
      "Displaying the current time in seconds",
    ],
    correctAnswer: 1,
    explanation:
      "Complex scientific modeling requires the high precision and large range offered by 64-bit double precision.",
  },
  {
    id: "csc221_305",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Floating-point hardware is usually built into the processor's FPU (Floating Point Unit).",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation:
      "While not explicitly in the text, modern processors use an FPU to handle these complex operations efficiently.",
  },
  {
    id: "csc221_306",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Floating-point numbers can represent 'Not a Number' (NaN).",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation: "NaN is a valid special value in the IEEE 754 standard.",
  },
  {
    id: "csc221_307",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Which of the following scientific notations is equivalent to 1,230?",
    options: [
      "$1.23 \\times 10^3$",
      "$1.23 \\times 10^2$",
      "$12.3 \\times 10^1$",
      "$1.23 \\times 10^{-3}$",
    ],
    correctAnswer: 0,
    explanation: "$1.23 \\times 1000 = 1230$.",
  },
  {
    id: "csc221_308",
    course: "CSC 221",
    chapter: "Chapter 6",
    text: "Floating point numbers are essential for aerospace calculations.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation:
      "Aerospace is explicitly listed as an application field for floating point accuracy and simulation.",
  },
];
