import { QuestionV2 } from "../../quiz-types";

export const csc221Chapter5: QuestionV2[] = [
  {
    id: "csc221_207",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "According to the Canvas slides, how is 'Data' defined?",
    options: [
      "The final information used for decision making",
      "Symbols that represent facts about people, things, events or ideas",
      "Electrical signals that power the computer",
      "The speed at which a processor executes instructions",
    ],
    correctAnswer: 1,
    explanation:
      "The slides define data as symbols that represent facts about people, things, events, or ideas.",
  },
  {
    id: "csc221_208",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "Which of the following is an example of data about a 'Thing'?",
    options: [
      "Blood group: O+",
      "Election year: 2027",
      "Laptop brand: HP",
      "Matric number: CSC/22/045",
    ],
    correctAnswer: 2,
    explanation:
      "A laptop brand describes a physical or non-living object, which falls under data about a 'Thing'.",
  },
  {
    id: "csc221_209",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "Data about an 'Idea' refers to facts describing concepts, events, or abstract entities.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation:
      "This is a direct definition from the 'Data about an Idea' slide in the Canvas document.",
  },
  {
    id: "csc221_210",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "In what forms can data be represented according to the lecture?",
    options: [
      "Letters of alphabets only",
      "Numerals and special symbols only",
      "Letters, special symbols, and numerals",
      "Voice commands and gestures only",
    ],
    correctAnswer: 2,
    explanation:
      "Data are in the form of letters of alphabets, special symbols, and numerals (decimal numbers).",
  },
  {
    id: "csc221_211",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "How is data represented internally to be manipulated by an electronic device?",
    options: [
      "As decimal integers (0-9)",
      "As electronic signals corresponding to $0$s and $1$s",
      "As physical ink marks on a disk",
      "As high-frequency sound waves",
    ],
    correctAnswer: 1,
    explanation:
      "Data are encoded in the form of $0$s and $1$s which correspond to electronic signals (switches being open or closed).",
  },
  {
    id: "csc221_212",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "What is the smallest unit of data in computing?",
    options: ["Byte", "Bit", "Word", "Character"],
    correctAnswer: 1,
    explanation:
      "A bit is the smallest unit of data in computing and can only be in one of two states: $0$ or $1$.",
  },
  {
    id: "csc221_213",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "A bit can represent more than two possible states at the same time.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 1,
    explanation: "A bit can only be in one of two possible states: $0$ or $1$.",
  },
  {
    id: "csc221_214",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "How many bits make up one Byte?",
    options: ["4 bits", "8 bits", "16 bits", "32 bits"],
    correctAnswer: 1,
    explanation:
      "The slides state that a group of 8 bits is called a Byte ($8$ bits = $1$ Byte).",
  },
  {
    id: "csc221_215",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "What is the total number of distinct data values that can be represented by 1 byte?",
    options: ["8", "128", "256", "1024"],
    correctAnswer: 2,
    explanation:
      "The total number of data that can be represented by 1 byte is $2^8$, which equals $256$.",
  },
  {
    id: "csc221_216",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "Which unit is primarily used to measure memory capacity or the size of a file?",
    options: ["Hertz", "Byte", "Word length", "IPS"],
    correctAnswer: 1,
    explanation:
      "A byte is used as a unit of measurement for memory capacity or file size.",
  },
  {
    id: "csc221_217",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "A Kilobyte consists of exactly 1,000 bytes.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 1,
    explanation: "A Kilobyte is $1,024$ ($2^{10}$) bytes, not $1,000$.",
  },
  {
    id: "csc221_218",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "Which of the following represents a Megabyte?",
    options: [
      "$2^{10}$ bytes",
      "$2^{20}$ bytes",
      "$2^{30}$ bytes",
      "$2^{40}$ bytes",
    ],
    correctAnswer: 1,
    explanation: "A Megabyte is $1,048,576$ or $2^{20}$ bytes.",
  },
  {
    id: "csc221_219",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "What is the size of a Gigabyte in bytes?",
    options: [
      "$2^{20}$ bytes",
      "$2^{30}$ bytes",
      "$2^{50}$ bytes",
      "$2^{60}$ bytes",
    ],
    correctAnswer: 1,
    explanation:
      "According to the table in the Canvas slides, a Gigabyte is $2^{30}$ bytes.",
  },
  {
    id: "csc221_220",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "Which of these is the largest unit of data representation listed in the slides?",
    options: ["Terabyte", "Petabyte", "Exabyte", "Gigabyte"],
    correctAnswer: 2,
    explanation: "The list in the slides goes up to Exabyte ($2^{60}$ bytes).",
  },
  {
    id: "csc221_221",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "What is a computer 'word'?",
    options: [
      "A set of 8 bits used for characters",
      "The basic unit of information stored or retrieved from memory",
      "The name given to the processor",
      "A single English word encoded in ASCII",
    ],
    correctAnswer: 1,
    explanation:
      "A word is the basic unit of information or group of bits that is stored or retrieved from computer memory.",
  },
  {
    id: "csc221_222",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "Which of the following are typical word lengths mentioned in the text?",
    options: [
      "2, 4, 6 bits",
      "8, 16, 32 bits",
      "10, 20, 30 bits",
      "100, 200, 300 bits",
    ],
    correctAnswer: 1,
    explanation: "Typical word lengths listed are 8, 16, and 32 bits.",
  },
  {
    id: "csc221_223",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "A larger word length generally makes a computer more powerful and faster.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation:
      "The larger the word length a computer has, the more powerful and faster it is.",
  },
  {
    id: "csc221_224",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "Which of these are considered 'Characters' in the context of data representation?",
    options: [
      "Letters A-Z only",
      "Digits 0-9 only",
      "Letters, digits, special symbols, and control characters",
      "Only non-printable formatting symbols",
    ],
    correctAnswer: 2,
    explanation:
      "Characters include letters, digits, special symbols (like +, ?, &), and control characters (like carriage return).",
  },
  {
    id: "csc221_225",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "Characters must be converted into binary form before they can be used in the computer.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation:
      "The text explicitly states characters must be converted to binary form for use in the computer.",
  },
  {
    id: "csc221_226",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "Which coding method was one of the early methods and uses 6 bits to represent a character?",
    options: ["ASCII", "EBCDIC", "BCD (Binary Coded Decimal)", "Unicode"],
    correctAnswer: 2,
    explanation:
      "BCD was an early coding method that used 6-bits to represent a character.",
  },
  {
    id: "csc221_227",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "EBCDIC is an 8-bit coding scheme that is an extension of:",
    options: ["ASCII", "BCD", "Unicode", "Positional logic"],
    correctAnswer: 1,
    explanation:
      "EBCDIC (Extended Binary Coded Decimal Interchange Code) is an extension of BCD.",
  },
  {
    id: "csc221_228",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "How many characters can the 8-bit EBCDIC scheme accommodate?",
    options: ["64", "128", "256", "512"],
    correctAnswer: 2,
    explanation:
      "As an 8-bit scheme, EBCDIC accommodates $2^8$ or $256$ characters.",
  },
  {
    id: "csc221_229",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "What does ASCII stand for?",
    options: [
      "Advanced Standard Code for Information Integration",
      "American Standard Code for Information Interchange",
      "African Standard Character Internal Index",
      "Application Specific Code for Intelligent Interface",
    ],
    correctAnswer: 1,
    explanation:
      "ASCII stands for American Standard Code for Information Interchange.",
  },
  {
    id: "csc221_230",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "Standard ASCII uses how many bits to represent a character?",
    options: ["6 bits", "7 bits", "8 bits", "16 bits"],
    correctAnswer: 1,
    explanation:
      "Standard ASCII uses 7-bits to represent a character, allowing for $2^7$ or $128$ characters.",
  },
  {
    id: "csc221_231",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "Which coding system is a 16-bit system capable of encoding characters for every language in the world?",
    options: ["BCD", "EBCDIC", "Extended ASCII", "Unicode"],
    correctAnswer: 3,
    explanation:
      "Unicode is a 16-bit system designed to encode the character of every language in the world.",
  },
  {
    id: "csc221_232",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "ASCII represents characters of every language in the world including Chinese and Arabic.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 1,
    explanation:
      "The slides state that ASCII only represents English alphabets and control characters; Unicode is needed for all world languages.",
  },
  {
    id: "csc221_233",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "In a positional number system, the value of a symbol depends on its:",
    options: ["Color", "Size", "Position in the number", "Weight in kilograms"],
    correctAnswer: 2,
    explanation:
      "In positional number systems, symbols represent values depending on their position in the number.",
  },
  {
    id: "csc221_234",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "Which of the following are the four most important number system bases mentioned?",
    options: ["2, 4, 6, 8", "2, 8, 10, 16", "1, 2, 3, 4", "5, 10, 15, 20"],
    correctAnswer: 1,
    explanation:
      "The four important bases are 2 (binary), 8 (octal), 10 (decimal), and 16 (hexadecimal).",
  },
  {
    id: "csc221_235",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "The binary number system has a base of:",
    options: ["1", "2", "8", "10"],
    correctAnswer: 1,
    explanation:
      "The binary number system uses just two digits {0, 1} and has a base of 2.",
  },
  {
    id: "csc221_236",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "What is the decimal value of the binary number $1011_2$?",
    options: ["10", "11", "13", "15"],
    correctAnswer: 1,
    explanation:
      "$1\times2^3 + 0\times2^2 + 1\times2^1 + 1\times2^0 = 8 + 0 + 2 + 1 = 11_{10}$.",
  },
  {
    id: "csc221_237",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "In a binary string, the 'msb' stands for:",
    options: [
      "Middle standard bit",
      "Main storage byte",
      "Most significant bit",
      "Minimum speed bit",
    ],
    correctAnswer: 2,
    explanation:
      "The binary digit furthest to the left is the most significant bit (msb).",
  },
  {
    id: "csc221_238",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "The octal number system uses symbols from:",
    options: ["0 to 8", "0 to 7", "1 to 8", "0 to 9"],
    correctAnswer: 1,
    explanation: "Octal uses eight symbols: 0, 1, 2, 3, 4, 5, 6, 7.",
  },
  {
    id: "csc221_239",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "What is the decimal equivalent of the octal number $2046_8$?",
    options: ["1024", "1062", "2046", "512"],
    correctAnswer: 1,
    explanation:
      "$(2\times8^3) + (0\times8^2) + (4\times8^1) + (6\times8^0) = 1024 + 0 + 32 + 6 = 1062_{10}$.",
  },
  {
    id: "csc221_240",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "The decimal number system uses weighting based on powers of:",
    options: ["2", "8", "10", "16"],
    correctAnswer: 2,
    explanation:
      "Decimal is a base-10 system, so weighting is 10 raised to the power of the position.",
  },
  {
    id: "csc221_241",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "The hexadecimal system uses symbols {0-9} and letters {A-F}. What decimal value does 'F' represent?",
    options: ["10", "14", "15", "16"],
    correctAnswer: 2,
    explanation: "In hexadecimal, A=10, B=11, C=12, D=13, E=14, and F=15.",
  },
  {
    id: "csc221_242",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "What is the decimal value of the hexadecimal number $A1F_{16}$?",
    options: ["2591", "2575", "10115", "3000"],
    correctAnswer: 0,
    explanation:
      "$(10\times16^2) + (1\times16^1) + (15\times16^0) = 2560 + 16 + 15 = 2591_{10}$.",
  },
  {
    id: "csc221_243",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "A single hexadecimal digit can represent how many bits of a binary number?",
    options: ["2 bits", "4 bits", "8 bits", "16 bits"],
    correctAnswer: 1,
    explanation:
      "A single hexadecimal digit is capable of representing a 4-bit binary number.",
  },
  {
    id: "csc221_244",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "To convert binary to hexadecimal, you should group binary digits into groups of:",
    options: ["2", "3", "4", "8"],
    correctAnswer: 2,
    explanation:
      "We convert binary to hexadecimal by grouping digits into 4's from right to left.",
  },
  {
    id: "csc221_245",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "The binary string $1011 | 0011 | 1010_2$ translates to which hexadecimal value?",
    options: ["$A3B_{16}$", "$B3A_{16}$", "$11310_{16}$", "$C2F_{16}$"],
    correctAnswer: 1,
    explanation: "1011=B, 0011=3, 1010=A. Thus, the value is $B3A_{16}$.",
  },
  {
    id: "csc221_246",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "The leftmost bit in Sign and Magnitude representation is used to indicate the sign.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation:
      "In Sign and Magnitude, the leftmost bit is the sign bit (0 for positive, 1 for negative).",
  },
  {
    id: "csc221_247",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "In signed binary representation, what decimal value does a sign bit of '1' typically represent?",
    options: ["Positive", "Negative", "Zero", "Infinity"],
    correctAnswer: 1,
    explanation:
      "By convention, 1 is used for negative numbers in signed representations.",
  },
  {
    id: "csc221_248",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "Using 8-bit Sign and Magnitude, how is $+20_{10}$ represented?",
    options: ["10010100", "00010100", "00010101", "11110100"],
    correctAnswer: 1,
    explanation:
      "Sign bit is 0 (positive), and 20 in binary is 10100. Padded to 8 bits: 00010100.",
  },
  {
    id: "csc221_249",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "Two's Complement is preferred over Sign and Magnitude because it allows addition and subtraction to be treated the same way.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation:
      "The slides state Two's Complement is more flexible as it allows addition and subtraction to be treated identically by the hardware.",
  },
  {
    id: "csc221_250",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "In an $n$-bit Two's Complement number, the most significant bit is given a weighting of:",
    options: ["$+2^{n-1}$", "$-2^{n-1}$", "$2^n$", "$-2^n$"],
    correctAnswer: 1,
    explanation:
      "In Two's Complement, the msb of an $n$-bit number is given a weighting of $-2^{n-1}$.",
  },
  {
    id: "csc221_251",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "What is the decimal value of the 8-bit Two's Complement number $10000111$?",
    options: ["$-7$", "$-121$", "$-128$", "$135$"],
    correctAnswer: 1,
    explanation: "Weighting: $-128 + (4+2+1) = -128 + 7 = -121_{10}$.",
  },
  {
    id: "csc221_252",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "What is the first step in converting a positive binary number to its negative Two's Complement equivalent?",
    options: [
      "Add 1 to the lsb",
      "Convert to one's complement (reverse all bits)",
      "Multiply by 2",
      "Divide by 10",
    ],
    correctAnswer: 1,
    explanation:
      "Step 1 is to convert to one's complement by reversing all bits ($1$ to $0$ and vice versa).",
  },
  {
    id: "csc221_253",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "After reversing bits in Two's Complement conversion, what is the final step?",
    options: [
      "Subtract 1 from the msb",
      "Add 1 to the least significant bit",
      "Shift all bits to the left",
      "Double the value",
    ],
    correctAnswer: 1,
    explanation:
      "After getting the one's complement, you must add 1 bit to the least significant bit.",
  },
  {
    id: "csc221_254",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "If $+2 = 00000010$, what is its 8-bit Two's Complement representation for $-2$?",
    options: ["11111101", "11111110", "10000010", "11111100"],
    correctAnswer: 1,
    explanation:
      "$+2 = 00000010$. One's complement = $11111101$. Add $1$ = $11111110$.",
  },
  {
    id: "csc221_255",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "The 8-bit Two's Complement representation $11110000$ has a decimal value of $-16$.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 0,
    explanation: "Weighting: $-128 + 64 + 32 + 16 = -128 + 112 = -16$.",
  },
  {
    id: "csc221_256",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "Which positional weighting is used for the decimal number $52.6$?",
    options: [
      "$5\times10^2 + 2\times10^1 + 6\times10^0$",
      "$5\times10^1 + 2\times10^0 + 6\times10^{-1}$",
      "$5\times2^1 + 2\times2^0 + 6\times2^{-1}$",
      "$5\times10^1 + 2\times10^1 + 6\times10^1$",
    ],
    correctAnswer: 1,
    explanation:
      "5 is in the tens position ($10^1$), 2 is in the units ($10^0$), and 6 is in the tenths ($10^{-1}$).",
  },
  {
    id: "csc221_257",
    course: "CSC 221",
    chapter: "Chapter 5",
    text: "Positional number systems use symbols to represent values based solely on their shape regardless of location.",
    options: ["True", "False", "Maybe", "I don't know"],
    correctAnswer: 1,
    explanation:
      "In positional systems, the location (position) of the symbol is what determines its actual value weight.",
  },
];
